# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prototype-phd',
                'doc_host': 'https://PaoloBova.github.io',
                'git_url': 'https://github.com/PaoloBova/prototype-phd',
                'lib_path': 'prototype_phd'},
  'syms': {'prototype_phd.core': {'prototype_phd.core.foo': ('core.html#foo', 'prototype_phd/core.py')}}}
